# Generated by Django 3.1.5 on 2021-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idCity', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('idShop', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idCity', models.IntegerField()),
                ('idStreet', models.IntegerField()),
                ('building', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('idStreet', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('idCity', models.IntegerField()),
            ],
        ),
    ]
